fix conda init

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -64,15 +64,12 @@ runs:
         echo "CONDA_BUILD_ENV_FILE: ${CONDA_BUILD_ENV_FILE}"
         cat "${CONDA_BUILD_ENV_FILE}"
 
+        echo 'source ${{ inputs.base_env_prefix }}/etc/profile.d/conda.sh'
+        source ${{ inputs.base_env_prefix }}/etc/profile.d/conda.sh
         echo "Checking that Conda is initialized"
         if ! command -v conda &> /dev/null; then
-          echo "Conda is not setup.  Attempting to set it up."
-          echo 'source ${{ inputs.base_env_prefix }}/etc/profile.d/conda.sh'
-          source ${{ inputs.base_env_prefix }}/etc/profile.d/conda.sh
-          if ! command -v conda &> /dev/null; then
-            echo "ERROR: Failed to setup setup Conda"
-            exit 1
-          fi
+          echo "ERROR: Conda is not setup."
+          exit 1
         fi
         echo "  Conda is initialized"
 
